# Generated by Django 3.0.3 on 2020-02-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200229_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cv',
            field=models.TextField(default='CV'),
        ),
    ]
