# Generated by Django 3.0.3 on 2020-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200306_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
