# Generated by Django 3.0.3 on 2020-03-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.FileField(default='avatar', upload_to=''),
        ),
    ]
